name: Blog.dvl.pl - An IT Hobbyist's Blog
description: An IT Hobbyist's Blog
meta_description: "An IT Hobbyist's Blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 50
baseurl: /
domain_name: 'http://blog.dvl.pl'
google_analytics: 'UA-3935714-1'
gems: [jekyll-paginate]

permalink: /article/:year/:month/:day/:title/

# Details for the RSS feed generator
url:            'http://blog.dvl.pl'
author:         'Karol Piczak'
